import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/app/main-layout";
import MenuLayout from "@/app/menu-layout";
import { cookies } from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = await cookies();
    const token = cookieStore.get("token")?.value;
    const isAuthenticated = !!token;

    const pathname = typeof window !== "undefined" ? window.location.pathname : "";

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MainLayout>
            {/* Показываем MenuLayout только если пользователь вошел и находится на /users */}
            {isAuthenticated && pathname.startsWith("/users") ? (
                <MenuLayout>{children}</MenuLayout>
            ) : (
                children
            )}
        </MainLayout>
        </body>
        </html>
    );
}
